### ISSUE TITLE
Provide for deploying to multiple stages

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomething/bertly#21]
Right now, we deploy to [a `dev` stage](https://github.com/DoSomething/bertly/blob/master/serverless.yml#L33) in what will become the production AWS account. Let's make sure that we set deployment stage [via the command line](https://serverless.com/framework/docs/providers/aws/cli-reference/deploy/) while deploying.

Bonus for making this as easy as possible. How much can/should we bundle into each deploy stage? Are there [stage-specific variables or secrets](https://serverless.com/framework/docs/providers/aws/guide/variables/) we'll want to tie to each stage?

The easiest first stage might be just to remove the YAML reference.

**Comment by DFurnes** [comment]
We made some progress on this by making the custom domain plugin [conditional per-stage](https://github.com/DoSomething/bertly/blob/6f3c0b6cc9c478bb66d53dea0960d0ebea6bbe01/serverless.yml#L24) in `serverless.yml` (see #22), but unfortuntately our production Lamdba function is still in the `dev` stage! Womp womp.

**Comment by DFurnes** [comment]
For now, we can deploy by hacking `serverless.yml` before a prod deploy:

```diff
--- a/serverless.yml
+++ b/serverless.yml
@@ -21,7 +21,7 @@ custom:
     basePath: ''
     stage: ${self:provider.stage}
     createRoute53Record: true
-    enabled: ${self:custom.domainEnabled.${opt:stage, self:provider.stage}}
+    enabled: true
```

Then it's just `sls --aws-profile serverless-production deploy` (using the production access ID and secret key stored in Lastpass).

**Comment by mshmsh5000** [comment]
🙃 That's from me, deploying to what would become our prod instance before I understand Serverless deploy stages! Ack.

**Comment by DFurnes** [comment]
We're figuring it out as we go! 😸

**Comment by DFurnes** [comment]
Alright, getting closer on this! We now have functional dev & QA environments:

- **Development:** https://s8b6x7cdy5.execute-api.us-east-1.amazonaws.com/dev/ ([bertly-dev-app](https://console.aws.amazon.com/lambda/home?region=us-east-1#/functions/bertly-dev-app))
- **QA:** https://lu8yl3tf72.execute-api.us-east-1.amazonaws.com/qa/ ([bertly-qa-app](https://console.aws.amazon.com/lambda/home?region=us-east-1#/functions/bertly-qa-app))

These can each be provisioned & deployed with `npm run deploy:dev` and `npm run deploy:qa`, and migrated by invoking the corresponding `migrate` function via the AWS CLI, e.g:

```
$ aws lambda invoke --function-name bertly-dev-migrate --profile serverless-dev output.txt
```

**Comment by DFurnes** [comment]
I think the next step is to figure out how we're going to migrate data from the Compose PostgreSQL and Redis instances onto their CloudFormation-provisioned equivalents when we push this to production, and make sure we can still hook into that Postgres instance from Quasar once we do.

**Comment by DFurnes** [comment]
Submitted a [support ticket](https://console.aws.amazon.com/support/v1#/case/?displayId=5252701271&language=en) to increase the VPC limit on our account. We also discussed consolidating our Sixpack instance in the Forge VPC into our main VPC, or moving it to Heroku.

**Comment by DFurnes** [comment]
Easy! Our support ticket was approved, and I'm kicking off another deploy now. 🤞

**Comment by DFurnes** [comment]
Created the new [bertly-prod](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn:aws:cloudformation:us-east-1:389428637636:stack%2Fbertly-prod%2Fc1faa7c0-9434-11e8-bb5b-503acac41efd) stack, accessible at https://yg1fy5f5kf.execute-api.us-east-1.amazonaws.com/prod for now (same Redis & API key as current prod, different Postgres).

**Comment by DFurnes** [comment]
I've added a `bertly-prod-source` source endpoint and `new-bertly-prod-target` target endpoint in AWS's Database Migration Service (configured to point to the new CloudFormation-provisioned prod instance). (**Note:** The existing production source, to be removed post-migration, is `bertly-clicks-prod-source`).


I think the next step is allowing the `Quasar-Hubble-DB-Proxy` security group to talk to Bertly's VPC.

**Comment by DFurnes** [comment]
I've created a `Quasar-to-Bertly` VPC peering connection `pcx-4f21a527` which connects the Quasar VPC to the new Bertly CloudFormation-provisioned VPC, and mapped `10.0.0.0/16` (the subnet where Bertly's RDS instance lives) to the Bertly VPC peering connection in Quasar's private route table.

**Comment by DFurnes** [comment]
And just added `10.0.2.0/24` and `10.0.3.0/24` port 5432 as inbound rules on the Quasar replication instance's `Quasar-Hubble-DB-Proxy` security group. Still timing out when I test the connection, though, so I think there's something I'm missing…

**Comment by mshmsh5000** [comment]
After resolving this ^^^ IRL, here is the CloudFormation config, extracted via [get-template](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/get-template.html):

https://gist.github.com/mshmsh5000/5ab6e7bc38c3f6ec994f619b1a43dcab

**Comment by DFurnes** [comment]
We've created a `bertly-old-to-new` migration task, and it's working perfectly! I created a link on the old production instance at https://dosome.click/r4a5p and am seeing the clicks increment over on the new instance [over here](https://yg1fy5f5kf.execute-api.us-east-1.amazonaws.com/prod/r4a5p/clicks).

**Comment by DFurnes** [comment]
So, next steps:

- [ ] Kill the old `bertly-dev` stack so we free up the domain resource.
- [ ] Re-enable custom domain in `serverless.yml` and deploy production stack.
- [ ] Hook up Quasar database migration to the new Bertly Postgres database.

**Comment by DFurnes** [comment]
Blah, one issue - the `bertly-old-to-new` database migration only moved the `clicks` table and not `alembic_version`, so Alembic can't run migrations. Unfortunately we renamed the existing Bertly source instead of using the new one I'd created, so we'd have to undo some work to fix this.

Instead, I've just run `alembic stamp 42a810a76302` to tell Alembic where we're at.

**Comment by mshmsh5000** [comment]
Smart -- makes sense.

CTO
@mshmsh5000 <http://twitter.com/mshmsh5000> @dosomething
<http://twitter.com/dosomething>

**Comment by DFurnes** [comment]
Updated documentation for deploying & running migrations in #41.

**Comment by DFurnes** [comment]
We've got three stages happily configured, so going to close this out!
