### ISSUE TITLE
Store user-agent in clicks table

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomething/bertly#37]
We need to store this to allow distinguishing among types of clicks, especially for preview-style autoload events.

Primary among these right now are iOS Messages preview events, for which there's an [identifiable but probably unstable user-agent string](https://stackoverflow.com/questions/41499402/what-is-the-user-agent-string-for-ios-macos-imessage/42094099#42094099).

Instead of having Bertly choose when not to record these links, it's more robust for Bertly just to record what is happening, and leave the interpretation to another layer.

**Comment by DFurnes** [comment]
This is deployed to production, and we've confirmed that it's being ingested into Quasar. 🌀
