### ISSUE TITLE
Consider short_url package instead of shorten

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomething/bertly#4]
Instead of `shorten`. The main reason is [short_url](https://pypi.python.org/pypi/short_url) offers a better pattern generation algorithm (for my taste):

>A bit-shuffling approach is used to avoid generating consecutive, predictable URLs. However, the algorithm is deterministic and will guarantee that no collisions will occur.

Will require a refactoring of link/key persistence, because this is baked in to `shorten` and not to `short_url`.

**Comment by DFurnes** [comment]
This was closed by #25.
